### ISSUE TITLE
[Enhancement Request] Setting to disable GM from 'Who has rolled more'

### ISSUE THREAD

**Issue by dacaz5** [Yosoy-Ed/simple-d20-stats#4]
Because the GM rolls more dice in general than players, statistically it's most likely for the GM to have rolled more Nat20s and Nat1s when looking at longer date ranges, but that's not very exciting for the players, so a setting to not include the GM as an option for that stat would be great.

**Comment by Yosoy-Ed** [comment]
I considered hiding it when "Allow players to see GM rolls" is disabled but I think players find joy seeing they have rolled more than  the GM sometimes, preccisely due to those odds. I will add it anyways.
