### ISSUE TITLE
[Bug] - MidiQOL hook error triggered when some module is not active

### ISSUE THREAD

**Issue by thatlonelybugbear** [Yosoy-Ed/simple-d20-stats#6]
```js
Hooks.on('midi-qol.RollComplete', (workflow) => {

    let chatMessage = workflow.chatCard;

    if (!game.settings.get('critic-message', 'disablemodule')) {

        detectroll(chatMessage);
    }
});
```
Not sure which module `critic-message` is, but this will always trigger an error if that is not active when checking for its setting.

You'd better do something like
```js
if (game.modules.get('critic-message')?.active && !game.settings.get('critic-message', 'disablemodule')) {
//do stuff
}
```

**Comment by thatlonelybugbear** [comment]
I just realised I didn't provide the actual error but it's just a common Hook error message, about `This is not a registered game setting`

**Comment by Yosoy-Ed** [comment]
thanks for the report, the other module is not needed, I just copy pasted some code from other module and I did not notice that line...

**Comment by Yosoy-Ed** [comment]
Fixed, please update and test.
Please let me know of any other issue you find.
