### ISSUE TITLE
Character sheet misalignment

### ISSUE THREAD

**Issue by ditzer252** [Yosoy-Ed/simple-d20-stats#7]
First, I want to thank you for this really great module.  The way that you present the stats is very clean and elegant, and I love the "pause" feature.
However, I've noticed a bug that appears when I have your module activated, where the header for the character sheets is being pushed to the right.  I'm on core version 12.331 and PF2e version 6.4.1

![image](https://github.com/user-attachments/assets/9fd37a4c-9091-49e4-bb52-217b69b73491)

**Comment by Yosoy-Ed** [comment]
Wow, didn't notice that. that's a crazy bug, hahaha. 
I will take a look, it should not mess with any other different window...
